[tasks.create-build]
workspace = false
command = "cargo"
cwd = "test-ws"
args = ["run", "-p", "teach-tech", "--", "build"]

[tasks.tidb-playground]
workspace = false
command = "tiup"
args = ["playground"]

[tasks.run-website]
workspace = false
command = "npm"
cwd = "teach-tech-web"
args = ["run", "dev"]

[tasks.run-api]
dependencies = ["create-build"]
workspace = false
command = "cargo"
cwd = "test-ws/teach-tech-built"
args = ["run", "--", "run"]

[tasks.reset-db]
dependencies = ["create-build"]
workspace = false
command = "cargo"
cwd = "test-ws/teach-tech-built"
args = ["run", "--", "reset-db"]

[tasks.playground]
workspace = false
run_task = { name = ["reset-db", "tidb-playground", "run-website"], fork = true, parallel = true }

[tasks.format-rust]
command = "cargo"
args = ["fmt"]

[tasks.format-web]
workspace = false
command = "npm"
cwd = "teach-tech-web"
args = ["run", "format"]

[tasks.format-all]
workspace = false
run_task = { name = ["format-rust", "format-web"]}